homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_timezone

default_config:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
